
xlua.hotfix(CS.Treasour,'CreatePrize',nil)
xlua.hotfix(CS.Gun,'Attack',nil)
xlua.hotfix(CS.ButterFly,'Start',nil)
xlua.hotfix(CS.Fire,'Start',nil)
xlua.hotfix(CS.Ice,'Start',nil)
xlua.hotfix(CS.Boss,'Start',nil)
xlua.hotfix(CS.DeffendBoss,'Start', nil)
xlua.hotfix(CS.InvisibleBoss,'Start', nil)
xlua.hotfix(CS.ButterFly,'Fire', nil)
xlua.hotfix(CS.Fire,'Attack', nil)
xlua.hotfix(CS.Ice,'ice', nil)
xlua.hotfix(CS.Gun,'GoldChange', nil)
xlua.hotfix(CS.Gun,'DiamandsChange', nil)
xlua.hotfix(CS.CreateFish,'Update', nil)
xlua.hotfix(CS.Gun,'UpGun', nil)
xlua.hotfix(CS.ButterFly,'Update', nil)
xlua.hotfix(CS.Ice,'Update', nil)
xlua.hotfix(CS.Treasour,'Update', nil)
xlua.hotfix(CS.GunChange,'Update', nil)
xlua.hotfix(CS.Fish,'TakeDamage', nil)
xlua.hotfix(CS.Boss,'TakeDamage', nil)
xlua.hotfix(CS.EmptyScript01,'Update', nil)
xlua.hotfix(CS.EmptyScript01,'OnTriggerEnter', nil)
xlua.hotfix(CS.EmptyScript01,'OnTriggerEnter', nil)
xlua.hotfix(CS.Gun,'Start', nil)

xlua.hotfix(CS.EmptyScript01,'EmptyMethod1', nil)